"""add_category_to_issues

Revision ID: cb78fde7783d
Revises: 89f649b8c3a8
Create Date: 2025-04-28 22:15:15.218536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb78fde7783d'
down_revision = '89f649b8c3a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'category')
    # ### end Alembic commands ### 